### PR TITLE
Lift to football-data API v4

### PR DESCRIPTION
**Pull request by dfrt82**
Hi Fritz,
I'm about to release the new version this week. I had a look at your implementation and adjusted the affected lines, hope I got all of them.
Daniel

### CODE REVIEW

**Comment by fritzrehde** [comment]
Is the api documentation for v4 on [football-data.org](https://football-data.org) yet? I can only find v2 documentation.

**Comment by dfrt82** [comment]
Nope, updating website right now. Hopefully able to release this evening...

**Comment by fritzrehde** [comment]
Cool! I will get to it as soon its out.

**Comment by fewieden** [comment]
@dfrt82 hi Daniel, looking forward to implementing v4 as well. Mind asking what happened to undocumented v3 :smile: ?

**Comment by dfrt82** [comment]
Well v3 is there... just without documentation :) And v4 docu is announced on the website now!

**Pull request merged**
